spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://127.0.0.1:16379"
          database: 1
        threads: 0
        nettyThreads: 0
        transportMode: "NIO"